---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

`jasmine` is a simple JSON parser

The following functions are implemented:

The following data sets are included:

### News

- Version 0.1.0.9000 released

### Installation

```{r eval=FALSE}
devtools::install_github("hrbrmstr/jasmine")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
options(width=120)
```

### Usage

```{r}
library(jasmine)

# current verison
packageVersion("jasmine")

get_keys('{ "dave" : "me", "henry" : 4, "steve" : [ "a", "b", "c" ]}')
```

### Test Results

```{r}
library(jasmine)
library(testthat)

date()

test_dir("tests/")
```

### Code of Conduct

Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). 
By participating in this project you agree to abide by its terms.
