// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_keys
CharacterVector get_keys(std::string js);
RcppExport SEXP jasmine_get_keys(SEXP jsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type js(jsSEXP);
    __result = Rcpp::wrap(get_keys(js));
    return __result;
END_RCPP
}
