# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get keys from a JSON input
#'
#' More info to hack at \url{http://zserge.com/jsmn.html}
#'
#' @param js length 1 character vector (the YUGE JSON string)
#' @export
#' @examples
#' get_keys('{ "dave" : "me", "henry" : 4, "steve" : [ "a", "b", "c" ]}')
get_keys <- function(js) {
    .Call('jasmine_get_keys', PACKAGE = 'jasmine', js)
}

